disabled_rules:
  - force_cast
  - force_try
  - cyclomatic_complexity
  - todo
  - nesting
  - line_length
  - identifier_name
  - trailing_whitespace
  - trailing_comma
  - inclusive_language
  - type_name
  - blanket_disable_command
  - void_function_in_ternary
  - orphaned_doc_comment

opt_in_rules:
  - array_init
  - closure_body_length
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - prefer_nil_literal
  - closure_end_indentation
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - redundant_void_return
  - prefer_self_type
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - large_tuple
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - xct_specific_matcher
  - yoda_condition

file_length:
  ignore_comment_only_lines: true

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import
  
line_length: 120
indentation:
  type: space
  width: 2
trailing_whitespace: true
file_header: true
type_name:
  min_length: 3
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id

redundant_optional_initialization: true
unused_closure_parameter: true
force_unwrapping: true
redundant_bool_literal: true
class_delegate_protocol: true
file_length:
  warning: 500
  error: 1000
