name: Run Danger on PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

  workflow_dispatch:

jobs:
  danger:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Danger and Danger-SwiftLint
        run: |
          gem install danger danger-swiftlint

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: danger --verbose
